// Code generated by the Encore 1.48.13 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly budget: budget.ServiceClient
    public readonly calendar: calendar.ServiceClient
    public readonly goals: goals.ServiceClient
    public readonly journal: journal.ServiceClient
    public readonly meals: meals.ServiceClient
    public readonly shopping: shopping.ServiceClient
    public readonly tasks: tasks.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.budget = new budget.ServiceClient(base)
        this.calendar = new calendar.ServiceClient(base)
        this.goals = new goals.ServiceClient(base)
        this.journal = new journal.ServiceClient(base)
        this.meals = new meals.ServiceClient(base)
        this.shopping = new shopping.ServiceClient(base)
        this.tasks = new tasks.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createCategory as api_budget_categories_createCategory,
    deleteCategory as api_budget_categories_deleteCategory,
    getCategories as api_budget_categories_getCategories,
    updateCategory as api_budget_categories_updateCategory
} from "~backend/budget/categories";
import {
    createTransaction as api_budget_transactions_createTransaction,
    deleteTransaction as api_budget_transactions_deleteTransaction,
    getSummary as api_budget_transactions_getSummary,
    getTransactions as api_budget_transactions_getTransactions,
    updateTransaction as api_budget_transactions_updateTransaction
} from "~backend/budget/transactions";

export namespace budget {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createCategory = this.createCategory.bind(this)
            this.createTransaction = this.createTransaction.bind(this)
            this.deleteCategory = this.deleteCategory.bind(this)
            this.deleteTransaction = this.deleteTransaction.bind(this)
            this.getCategories = this.getCategories.bind(this)
            this.getSummary = this.getSummary.bind(this)
            this.getTransactions = this.getTransactions.bind(this)
            this.updateCategory = this.updateCategory.bind(this)
            this.updateTransaction = this.updateTransaction.bind(this)
        }

        /**
         * Creates a new budget category.
         */
        public async createCategory(params: RequestType<typeof api_budget_categories_createCategory>): Promise<ResponseType<typeof api_budget_categories_createCategory>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/budget/categories`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_budget_categories_createCategory>
        }

        /**
         * Creates a new transaction.
         */
        public async createTransaction(params: RequestType<typeof api_budget_transactions_createTransaction>): Promise<ResponseType<typeof api_budget_transactions_createTransaction>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/budget/transactions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_budget_transactions_createTransaction>
        }

        /**
         * Deletes a budget category.
         */
        public async deleteCategory(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/budget/categories/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a transaction.
         */
        public async deleteTransaction(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/budget/transactions/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Gets all budget categories for the current user.
         */
        public async getCategories(): Promise<ResponseType<typeof api_budget_categories_getCategories>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/budget/categories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_budget_categories_getCategories>
        }

        /**
         * Gets budget summary for the current user.
         */
        public async getSummary(): Promise<ResponseType<typeof api_budget_transactions_getSummary>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/budget/summary`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_budget_transactions_getSummary>
        }

        /**
         * Gets all transactions for the current user.
         */
        public async getTransactions(): Promise<ResponseType<typeof api_budget_transactions_getTransactions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/budget/transactions`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_budget_transactions_getTransactions>
        }

        /**
         * Updates a budget category.
         */
        public async updateCategory(params: RequestType<typeof api_budget_categories_updateCategory>): Promise<ResponseType<typeof api_budget_categories_updateCategory>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                name: params.name,
                type: params.type,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/budget/categories/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_budget_categories_updateCategory>
        }

        /**
         * Updates a transaction.
         */
        public async updateTransaction(params: RequestType<typeof api_budget_transactions_updateTransaction>): Promise<ResponseType<typeof api_budget_transactions_updateTransaction>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                amount:        params.amount,
                "category_id": params["category_id"],
                date:          params.date,
                description:   params.description,
                type:          params.type,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/budget/transactions/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_budget_transactions_updateTransaction>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createEvent as api_calendar_events_createEvent,
    deleteEvent as api_calendar_events_deleteEvent,
    getEvent as api_calendar_events_getEvent,
    getEvents as api_calendar_events_getEvents,
    updateEvent as api_calendar_events_updateEvent
} from "~backend/calendar/events";

export namespace calendar {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createEvent = this.createEvent.bind(this)
            this.deleteEvent = this.deleteEvent.bind(this)
            this.getEvent = this.getEvent.bind(this)
            this.getEvents = this.getEvents.bind(this)
            this.updateEvent = this.updateEvent.bind(this)
        }

        /**
         * Creates a new calendar event.
         */
        public async createEvent(params: RequestType<typeof api_calendar_events_createEvent>): Promise<ResponseType<typeof api_calendar_events_createEvent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calendar/events`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_calendar_events_createEvent>
        }

        /**
         * Deletes an event.
         */
        public async deleteEvent(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/calendar/events/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Gets a specific event.
         */
        public async getEvent(params: { id: number }): Promise<ResponseType<typeof api_calendar_events_getEvent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calendar/events/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_calendar_events_getEvent>
        }

        /**
         * Gets all events for the current user.
         */
        public async getEvents(): Promise<ResponseType<typeof api_calendar_events_getEvents>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calendar/events`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_calendar_events_getEvents>
        }

        /**
         * Updates an event.
         */
        public async updateEvent(params: RequestType<typeof api_calendar_events_updateEvent>): Promise<ResponseType<typeof api_calendar_events_updateEvent>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                date:        params.date,
                description: params.description,
                title:       params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calendar/events/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_calendar_events_updateEvent>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createGoal as api_goals_goals_createGoal,
    deleteGoal as api_goals_goals_deleteGoal,
    getGoal as api_goals_goals_getGoal,
    getGoals as api_goals_goals_getGoals,
    updateGoal as api_goals_goals_updateGoal
} from "~backend/goals/goals";

export namespace goals {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createGoal = this.createGoal.bind(this)
            this.deleteGoal = this.deleteGoal.bind(this)
            this.getGoal = this.getGoal.bind(this)
            this.getGoals = this.getGoals.bind(this)
            this.updateGoal = this.updateGoal.bind(this)
        }

        /**
         * Creates a new goal.
         */
        public async createGoal(params: RequestType<typeof api_goals_goals_createGoal>): Promise<ResponseType<typeof api_goals_goals_createGoal>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/goals`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_goals_goals_createGoal>
        }

        /**
         * Deletes a goal.
         */
        public async deleteGoal(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/goals/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Gets a specific goal.
         */
        public async getGoal(params: { id: number }): Promise<ResponseType<typeof api_goals_goals_getGoal>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/goals/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_goals_goals_getGoal>
        }

        /**
         * Gets all goals for the current user.
         */
        public async getGoals(): Promise<ResponseType<typeof api_goals_goals_getGoals>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/goals`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_goals_goals_getGoals>
        }

        /**
         * Updates a goal.
         */
        public async updateGoal(params: RequestType<typeof api_goals_goals_updateGoal>): Promise<ResponseType<typeof api_goals_goals_updateGoal>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "current_value": params["current_value"],
                description:     params.description,
                status:          params.status,
                "target_date":   params["target_date"],
                "target_value":  params["target_value"],
                title:           params.title,
                unit:            params.unit,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/goals/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_goals_goals_updateGoal>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createEntry as api_journal_entries_createEntry,
    deleteEntry as api_journal_entries_deleteEntry,
    getEntries as api_journal_entries_getEntries,
    getEntry as api_journal_entries_getEntry,
    updateEntry as api_journal_entries_updateEntry
} from "~backend/journal/entries";

export namespace journal {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createEntry = this.createEntry.bind(this)
            this.deleteEntry = this.deleteEntry.bind(this)
            this.getEntries = this.getEntries.bind(this)
            this.getEntry = this.getEntry.bind(this)
            this.updateEntry = this.updateEntry.bind(this)
        }

        /**
         * Creates a new journal entry.
         */
        public async createEntry(params: RequestType<typeof api_journal_entries_createEntry>): Promise<ResponseType<typeof api_journal_entries_createEntry>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/journal/entries`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_journal_entries_createEntry>
        }

        /**
         * Deletes a journal entry.
         */
        public async deleteEntry(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/journal/entries/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Gets all journal entries for the current user.
         */
        public async getEntries(): Promise<ResponseType<typeof api_journal_entries_getEntries>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/journal/entries`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_journal_entries_getEntries>
        }

        /**
         * Gets a specific journal entry.
         */
        public async getEntry(params: { id: number }): Promise<ResponseType<typeof api_journal_entries_getEntry>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/journal/entries/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_journal_entries_getEntry>
        }

        /**
         * Updates a journal entry.
         */
        public async updateEntry(params: RequestType<typeof api_journal_entries_updateEntry>): Promise<ResponseType<typeof api_journal_entries_updateEntry>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                content: params.content,
                date:    params.date,
                mood:    params.mood,
                title:   params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/journal/entries/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_journal_entries_updateEntry>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getMealPlan as api_meals_meal_plans_getMealPlan,
    getWeekIngredients as api_meals_meal_plans_getWeekIngredients,
    removeMeal as api_meals_meal_plans_removeMeal,
    setMeal as api_meals_meal_plans_setMeal
} from "~backend/meals/meal_plans";
import {
    createRecipe as api_meals_recipes_createRecipe,
    deleteRecipe as api_meals_recipes_deleteRecipe,
    getRecipe as api_meals_recipes_getRecipe,
    getRecipes as api_meals_recipes_getRecipes,
    updateRecipe as api_meals_recipes_updateRecipe
} from "~backend/meals/recipes";

export namespace meals {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createRecipe = this.createRecipe.bind(this)
            this.deleteRecipe = this.deleteRecipe.bind(this)
            this.getMealPlan = this.getMealPlan.bind(this)
            this.getRecipe = this.getRecipe.bind(this)
            this.getRecipes = this.getRecipes.bind(this)
            this.getWeekIngredients = this.getWeekIngredients.bind(this)
            this.removeMeal = this.removeMeal.bind(this)
            this.setMeal = this.setMeal.bind(this)
            this.updateRecipe = this.updateRecipe.bind(this)
        }

        /**
         * Creates a new recipe.
         */
        public async createRecipe(params: RequestType<typeof api_meals_recipes_createRecipe>): Promise<ResponseType<typeof api_meals_recipes_createRecipe>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_meals_recipes_createRecipe>
        }

        /**
         * Deletes a recipe.
         */
        public async deleteRecipe(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/recipes/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Gets or creates a meal plan for a specific week.
         */
        public async getMealPlan(params: RequestType<typeof api_meals_meal_plans_getMealPlan>): Promise<ResponseType<typeof api_meals_meal_plans_getMealPlan>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "week_of": params["week_of"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/meal-plans`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_meals_meal_plans_getMealPlan>
        }

        /**
         * Gets a specific recipe with ingredients.
         */
        public async getRecipe(params: { id: number }): Promise<ResponseType<typeof api_meals_recipes_getRecipe>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_meals_recipes_getRecipe>
        }

        /**
         * Gets all recipes for the current user.
         */
        public async getRecipes(): Promise<ResponseType<typeof api_meals_recipes_getRecipes>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_meals_recipes_getRecipes>
        }

        /**
         * Gets all ingredients needed for a week's meal plan.
         */
        public async getWeekIngredients(params: RequestType<typeof api_meals_meal_plans_getWeekIngredients>): Promise<ResponseType<typeof api_meals_meal_plans_getWeekIngredients>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "week_of": params["week_of"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/meal-plans/ingredients`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_meals_meal_plans_getWeekIngredients>
        }

        /**
         * Removes a meal from a specific day and meal type.
         */
        public async removeMeal(params: RequestType<typeof api_meals_meal_plans_removeMeal>): Promise<void> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "custom_meal": params["custom_meal"],
                "day_of_week": String(params["day_of_week"]),
                "meal_type":   String(params["meal_type"]),
                "recipe_id":   params["recipe_id"] === undefined ? undefined : String(params["recipe_id"]),
                "week_of":     params["week_of"],
            })

            await this.baseClient.callTypedAPI(`/meal-plans/meals`, {query, method: "DELETE", body: undefined})
        }

        /**
         * Sets a meal for a specific day and meal type.
         */
        public async setMeal(params: RequestType<typeof api_meals_meal_plans_setMeal>): Promise<ResponseType<typeof api_meals_meal_plans_setMeal>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/meal-plans/meals`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_meals_meal_plans_setMeal>
        }

        /**
         * Updates a recipe.
         */
        public async updateRecipe(params: RequestType<typeof api_meals_recipes_updateRecipe>): Promise<ResponseType<typeof api_meals_recipes_updateRecipe>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                ingredients:  params.ingredients,
                instructions: params.instructions,
                name:         params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_meals_recipes_updateRecipe>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    addItems as api_shopping_items_addItems,
    createItem as api_shopping_items_createItem,
    deleteItem as api_shopping_items_deleteItem,
    uncheckAllItems as api_shopping_items_uncheckAllItems,
    updateItem as api_shopping_items_updateItem
} from "~backend/shopping/items";
import {
    createList as api_shopping_lists_createList,
    deleteList as api_shopping_lists_deleteList,
    getList as api_shopping_lists_getList,
    getLists as api_shopping_lists_getLists,
    updateList as api_shopping_lists_updateList
} from "~backend/shopping/lists";

export namespace shopping {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addItems = this.addItems.bind(this)
            this.createItem = this.createItem.bind(this)
            this.createList = this.createList.bind(this)
            this.deleteItem = this.deleteItem.bind(this)
            this.deleteList = this.deleteList.bind(this)
            this.getList = this.getList.bind(this)
            this.getLists = this.getLists.bind(this)
            this.uncheckAllItems = this.uncheckAllItems.bind(this)
            this.updateItem = this.updateItem.bind(this)
            this.updateList = this.updateList.bind(this)
        }

        /**
         * Adds multiple items to a shopping list.
         */
        public async addItems(params: RequestType<typeof api_shopping_items_addItems>): Promise<ResponseType<typeof api_shopping_items_addItems>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                items: params.items,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/lists/${encodeURIComponent(params.list_id)}/items/bulk`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_items_addItems>
        }

        /**
         * Creates a new shopping item.
         */
        public async createItem(params: RequestType<typeof api_shopping_items_createItem>): Promise<ResponseType<typeof api_shopping_items_createItem>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/items`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_items_createItem>
        }

        /**
         * Creates a new shopping list.
         */
        public async createList(params: RequestType<typeof api_shopping_lists_createList>): Promise<ResponseType<typeof api_shopping_lists_createList>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/lists`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_lists_createList>
        }

        /**
         * Deletes a shopping item.
         */
        public async deleteItem(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/shopping/items/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a shopping list.
         */
        public async deleteList(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/shopping/lists/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Gets a specific shopping list with all its items.
         */
        public async getList(params: { id: number }): Promise<ResponseType<typeof api_shopping_lists_getList>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/lists/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_lists_getList>
        }

        /**
         * Gets all shopping lists for the current user.
         */
        public async getLists(): Promise<ResponseType<typeof api_shopping_lists_getLists>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/lists`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_lists_getLists>
        }

        /**
         * Unchecks all items in a shopping list.
         */
        public async uncheckAllItems(params: { list_id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/shopping/lists/${encodeURIComponent(params.list_id)}/uncheck-all`, {method: "POST", body: undefined})
        }

        /**
         * Updates a shopping item.
         */
        public async updateItem(params: RequestType<typeof api_shopping_items_updateItem>): Promise<ResponseType<typeof api_shopping_items_updateItem>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "is_checked": params["is_checked"],
                name:         params.name,
                position:     params.position,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/items/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_items_updateItem>
        }

        /**
         * Updates a shopping list.
         */
        public async updateList(params: RequestType<typeof api_shopping_lists_updateList>): Promise<ResponseType<typeof api_shopping_lists_updateList>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                title: params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/lists/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_lists_updateList>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createAttachment as api_tasks_attachments_createAttachment,
    deleteAttachment as api_tasks_attachments_deleteAttachment,
    getCardAttachments as api_tasks_attachments_getCardAttachments
} from "~backend/tasks/attachments";
import {
    createBoard as api_tasks_boards_createBoard,
    getBoard as api_tasks_boards_getBoard,
    listBoards as api_tasks_boards_listBoards
} from "~backend/tasks/boards";
import {
    addCardMember as api_tasks_cards_addCardMember,
    createCard as api_tasks_cards_createCard,
    deleteCard as api_tasks_cards_deleteCard,
    getCard as api_tasks_cards_getCard,
    getTodayCards as api_tasks_cards_getTodayCards,
    removeCardMember as api_tasks_cards_removeCardMember,
    updateCard as api_tasks_cards_updateCard
} from "~backend/tasks/cards";
import {
    createChecklist as api_tasks_checklists_createChecklist,
    createChecklistItem as api_tasks_checklists_createChecklistItem,
    deleteChecklist as api_tasks_checklists_deleteChecklist,
    deleteChecklistItem as api_tasks_checklists_deleteChecklistItem,
    updateChecklist as api_tasks_checklists_updateChecklist,
    updateChecklistItem as api_tasks_checklists_updateChecklistItem
} from "~backend/tasks/checklists";
import {
    createComment as api_tasks_comments_createComment,
    deleteComment as api_tasks_comments_deleteComment,
    getCardComments as api_tasks_comments_getCardComments,
    updateComment as api_tasks_comments_updateComment
} from "~backend/tasks/comments";
import {
    createList as api_tasks_lists_createList,
    deleteList as api_tasks_lists_deleteList,
    updateList as api_tasks_lists_updateList
} from "~backend/tasks/lists";

export namespace tasks {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addCardMember = this.addCardMember.bind(this)
            this.createAttachment = this.createAttachment.bind(this)
            this.createBoard = this.createBoard.bind(this)
            this.createCard = this.createCard.bind(this)
            this.createChecklist = this.createChecklist.bind(this)
            this.createChecklistItem = this.createChecklistItem.bind(this)
            this.createComment = this.createComment.bind(this)
            this.createList = this.createList.bind(this)
            this.deleteAttachment = this.deleteAttachment.bind(this)
            this.deleteCard = this.deleteCard.bind(this)
            this.deleteChecklist = this.deleteChecklist.bind(this)
            this.deleteChecklistItem = this.deleteChecklistItem.bind(this)
            this.deleteComment = this.deleteComment.bind(this)
            this.deleteList = this.deleteList.bind(this)
            this.getBoard = this.getBoard.bind(this)
            this.getCard = this.getCard.bind(this)
            this.getCardAttachments = this.getCardAttachments.bind(this)
            this.getCardComments = this.getCardComments.bind(this)
            this.getTodayCards = this.getTodayCards.bind(this)
            this.listBoards = this.listBoards.bind(this)
            this.removeCardMember = this.removeCardMember.bind(this)
            this.updateCard = this.updateCard.bind(this)
            this.updateChecklist = this.updateChecklist.bind(this)
            this.updateChecklistItem = this.updateChecklistItem.bind(this)
            this.updateComment = this.updateComment.bind(this)
            this.updateList = this.updateList.bind(this)
        }

        /**
         * Adds a member to a card.
         */
        public async addCardMember(params: RequestType<typeof api_tasks_cards_addCardMember>): Promise<void> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "user_id": params["user_id"],
            }

            await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.card_id)}/members`, {method: "POST", body: JSON.stringify(body)})
        }

        /**
         * Creates a new attachment for a card.
         */
        public async createAttachment(params: RequestType<typeof api_tasks_attachments_createAttachment>): Promise<ResponseType<typeof api_tasks_attachments_createAttachment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/attachments`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_attachments_createAttachment>
        }

        /**
         * Creates a new board.
         */
        public async createBoard(params: RequestType<typeof api_tasks_boards_createBoard>): Promise<ResponseType<typeof api_tasks_boards_createBoard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/boards`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_boards_createBoard>
        }

        /**
         * Creates a new card in a list.
         */
        public async createCard(params: RequestType<typeof api_tasks_cards_createCard>): Promise<ResponseType<typeof api_tasks_cards_createCard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_cards_createCard>
        }

        /**
         * Creates a new checklist for a card.
         */
        public async createChecklist(params: RequestType<typeof api_tasks_checklists_createChecklist>): Promise<ResponseType<typeof api_tasks_checklists_createChecklist>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/checklists`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_checklists_createChecklist>
        }

        /**
         * Creates a new checklist item.
         */
        public async createChecklistItem(params: RequestType<typeof api_tasks_checklists_createChecklistItem>): Promise<ResponseType<typeof api_tasks_checklists_createChecklistItem>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/checklist-items`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_checklists_createChecklistItem>
        }

        /**
         * Creates a new comment on a card.
         */
        public async createComment(params: RequestType<typeof api_tasks_comments_createComment>): Promise<ResponseType<typeof api_tasks_comments_createComment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/comments`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_comments_createComment>
        }

        /**
         * Creates a new list in a board.
         */
        public async createList(params: RequestType<typeof api_tasks_lists_createList>): Promise<ResponseType<typeof api_tasks_lists_createList>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/lists`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_lists_createList>
        }

        /**
         * Deletes an attachment.
         */
        public async deleteAttachment(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/attachments/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a card.
         */
        public async deleteCard(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a checklist.
         */
        public async deleteChecklist(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/checklists/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a checklist item.
         */
        public async deleteChecklistItem(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/checklist-items/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a comment.
         */
        public async deleteComment(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/comments/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a list.
         */
        public async deleteList(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/lists/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Gets a specific board with all its lists and cards.
         */
        public async getBoard(params: { id: number }): Promise<ResponseType<typeof api_tasks_boards_getBoard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/boards/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_boards_getBoard>
        }

        /**
         * Gets a specific card with all its details.
         */
        public async getCard(params: { id: number }): Promise<ResponseType<typeof api_tasks_cards_getCard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_cards_getCard>
        }

        /**
         * Gets all attachments for a card.
         */
        public async getCardAttachments(params: { card_id: number }): Promise<ResponseType<typeof api_tasks_attachments_getCardAttachments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.card_id)}/attachments`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_attachments_getCardAttachments>
        }

        /**
         * Gets all comments for a card.
         */
        public async getCardComments(params: { card_id: number }): Promise<ResponseType<typeof api_tasks_comments_getCardComments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.card_id)}/comments`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_comments_getCardComments>
        }

        /**
         * Gets all cards due today.
         */
        public async getTodayCards(): Promise<ResponseType<typeof api_tasks_cards_getTodayCards>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/today`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_cards_getTodayCards>
        }

        /**
         * Lists all boards.
         */
        public async listBoards(): Promise<ResponseType<typeof api_tasks_boards_listBoards>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/boards`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_boards_listBoards>
        }

        /**
         * Removes a member from a card.
         */
        public async removeCardMember(params: { card_id: number, user_id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.card_id)}/members/${encodeURIComponent(params.user_id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Updates a card.
         */
        public async updateCard(params: RequestType<typeof api_tasks_cards_updateCard>): Promise<ResponseType<typeof api_tasks_cards_updateCard>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                "due_date":  params["due_date"],
                labels:      params.labels,
                "list_id":   params["list_id"],
                position:    params.position,
                title:       params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_cards_updateCard>
        }

        /**
         * Updates a checklist.
         */
        public async updateChecklist(params: RequestType<typeof api_tasks_checklists_updateChecklist>): Promise<ResponseType<typeof api_tasks_checklists_updateChecklist>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                position: params.position,
                title:    params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/checklists/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_checklists_updateChecklist>
        }

        /**
         * Updates a checklist item.
         */
        public async updateChecklistItem(params: RequestType<typeof api_tasks_checklists_updateChecklistItem>): Promise<ResponseType<typeof api_tasks_checklists_updateChecklistItem>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                completed: params.completed,
                position:  params.position,
                title:     params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/checklist-items/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_checklists_updateChecklistItem>
        }

        /**
         * Updates a comment.
         */
        public async updateComment(params: RequestType<typeof api_tasks_comments_updateComment>): Promise<ResponseType<typeof api_tasks_comments_updateComment>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                content: params.content,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/comments/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_comments_updateComment>
        }

        /**
         * Updates a list.
         */
        public async updateList(params: RequestType<typeof api_tasks_lists_updateList>): Promise<ResponseType<typeof api_tasks_lists_updateList>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                position: params.position,
                title:    params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/lists/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_lists_updateList>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.13)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
